plank:
  default_decoration_config:
    utility_images: # using the tag we identified above
      clonerefs: "gcr.io/k8s-prow/clonerefs:v20191121-1ff2207db"
      initupload: "gcr.io/k8s-prow/initupload:v20191121-1ff2207db"
      entrypoint: "gcr.io/k8s-prow/entrypoint:v20191121-1ff2207db"
      sidecar: "gcr.io/k8s-prow/sidecar:v20191121-1ff2207db"
    gcs_configuration:
      bucket: prow-artifacts-tekton-257312 # the bucket we just made
      path_strategy: explicit
    gcs_credentials_secret: gcs-credentials # the secret we just made

postsubmits:
  cheesydev-labs/java-app:
  - name: test-postsubmit
    decorate: true
    always_run: true
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
presubmits:
  cheesydev-labs/java-app:
  - name: test-presubmit
    decorate: true
    always_run: true
    skip_report: false
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
  - name: test-javaapp-presubmit
    decorate: true
    always_run: true
    spec:
      containers:
      - image: openjdk:11-jdk-slim
        command: ["./gradlew"]
        args: ["--no-daemon", "test"]
